#+TITLE: Notes on Computation Structures
#+AUTHOR: Linerre <zlinerre@gmail.com>

* Announcement
The course was previously known as 6.004 and now its code changed to 6.191.

#+BEGIN_QUOTE
Welcome to the Fall 2023 semester of 6.1910 which we will call 6.191 (also known as 6.004)!
#+END_QUOTE
from course official site:[[https://6191.mit.edu/fall23]]

* Schedule
2 lectures and 1 lab each week, as illustrated at [[https://6191.mit.edu/fall23/schedule]]

About 23 topics in total.  The course is usually delivered in Fall and Spring semesters.

* Versions
There are a couple of versions available for this course.  The table below lists a few that can be easily found by a single Google search.

| Year | Site        | Materials             | Lecture Videos |
|------+-------------+-----------------------+----------------|
| 2009 | [[https://ocw.mit.edu/courses/6-004-computation-structures-spring-2009/][2009-Spring]] | [[https://ocw.mit.edu/courses/6-004-computation-structures-spring-2009/download/][MIT OpenCourseWare]]    | NA             |
| 2017 | [[https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/][2017-Spring]] | [[https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/pages/syllabus/][MIT OpenCourseWare]][1] | [[https://youtube.com/playlist?list=PLUl4u3cNGP62WVs95MNq3dQBqY2vGOtQ2&si=KLMhgGDRrluA7D_a][YouTube]]        |
| 2018 | NA          | [[https://6191.mit.edu/fall23/resources][6.191 Resources]]       | [[https://youtube.com/playlist?list=PLDSlqjcPpoL64CJdF0Qee5oWqGS6we_Yu&si=JvM51x8XKzCZoZii][YouTube]][2]     |
|------+-------------+-----------------------+----------------|
[1] The annotated slides are embedded in each lecture.  Navigate the left sidebar to find them.
[2] The official site (https://6004.mit.edu/web/fall18/resources) mentioned in the video list is /not/ accessible to non-mit students, but under the "Material" tab the required/needed resources are available for download.

Matthew Towers in his [[https://www.homepages.ucl.ac.uk/~ucahmto/elearning/2020/04/13/6.004_and_CS143.html][6.004 and CS143 (Compilers)]] post gives a quick rundown of different 6.004 versions and (possible) reasons for why the later versions become more inaccessible (mainly, academic integrity).

In subreddit r/mit there is [[https://www.reddit.com/r/mit/comments/c1nsl3/mit_6004/][this thread]] where different versions were discussed and suggestions were given to students based on their backgrounds (i.e. computer science v.s. electrical engineering).
